# -*- coding: utf-8 -*-
"""predict_category.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEr8UUBYy_8lugAaNDcIFWjMY5HW8oVt
"""

import pickle

# Încărcarea modelului
with open("product_classifier.pkl", "rb") as file:
    model = pickle.load(file)

# Funcția de predicție

def predict_category(product_title):
    prediction = model.predict([product_title])
    return prediction[0]

# Test
if __name__ == "__main__":
    product = input("Introdu titlul produsului: ")
    category = predict_category(product)
    print("\nCategoria prezisă:", category)